import { useState, useRef, useCallback } from "react";
const MAX_TOKENS_DYN=320,MAX_TOKENS_RECOS=5000,MAX_TOKENS_CHAT=900;
const FREE_STEPS=[{id:"budget",label:"Profil fondamental",num:"tape 1 / 4",q:"Quel est votre budget maximum pour ce cadeau ?",hint:"Entrez un montant en euros",placeholder:"500",type:"number",validate:(v)=>{const n=parseInt(v.replace(/\D/g,""),10);if(isNaN(n)||n<1)return"Montant invalide.";if(n>50000)return"Max 50 000.";return null}},{id:"age",label:"Age",num:"tape 2 / 4",q:"Quel age a la personne ?",hint:"L'age oriente le style.",placeholder:"34",type:"number",validate:(v)=>{const n=parseInt(v.replace(/\D/g,""),10);if(isNaN(n)||n<1)return"Age invalide.";return null}},{id:"city",label:"Ville",num:"tape 3 / 4",q:"Dans quelle ville habite cette personne ?",hint:"Ex: Paris",placeholder:"Paris",type:"text",validate:(v)=>v.trim().length<2?"Ville invalide.":null},{id:"hobby",label:"Passions",num:"tape 4 / 4",q:"A-t-elle une passion ou un hobby ?",hint:"Laissez vide si inconnu.",placeholder:"Ex: jazz, montres...",type:"textarea",validate:()=>null}];
const FIXED_BQ=[{q:"La technologie l'intresse-t-elle ?",theme:"TECH",phase:"Axe tech..."},{q:"Apprcie-t-elle la gastronomie ?",theme:"GASTRO",phase:"Axe gastro..."},{q:"Est-elle attire par le luxe ?",theme:"LUXE",phase:"Axe luxe..."},{q:"La mode fait-elle partie de son univers ?",theme:"MODE",phase:"Axe mode..."},{q:"Est-elle passionne d'art ou culture ?",theme:"ART",phase:"Axe art..."},{q:"Pratique-t-elle un sport ?",theme:"SPORT",phase:"Axe sport..."},{q:"Les voyages sont-ils importants ?",theme:"VOYAGE",phase:"Axe voyage..."},{q:"A-t-elle des valeurs cologiques ?",theme:"NATURE",phase:"Axe nature..."},{q:"Est-elle sensible  l'adrnaline ?",theme:"ADRENALINE",phase:"Axe adrnaline..."},{q:"Le foyer et l'intrieur sont-ils importants ?",theme:"MAISON",phase:"Axe maison..."},{q:"Souhaitez-vous un cadeau personnalis ?",theme:null,phase:"Personnalisation...",isPerso:true}];
function safeParseJson(raw){try{return JSON.parse(raw.replace(/json\s*/g,"").replace(/\s*/g,"").trim())}catch{return null}}
async function callProxy(messages,system,maxTokens){const res=await fetch("/api/giftmind",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages,system,maxTokens})});if(!res.ok)throw new Error("API error");const data=await res.json();return data.text||""}
export default function GiftMindOS(){
const[screen,setScreen]=useState("intro");
const[curFree,setCurFree]=useState(0);
const[freeVals,setFreeVals]=useState({budget:"",age:"",city:"",hobby:""});
const[freeErr,setFreeErr]=useState("");
const[curBin,setCurBin]=useState(0);
const[inDynamic,setInDynamic]=useState(false);
const[fixedAnswers,setFixedAnswers]=useState([]);
const[dynQuestions,setDynQuestions]=useState([]);
const[conf,setConf]=useState(0);
const[confPhase,setConfPhase]=useState("Initialisation");
const[thinking,setThinking]=useState(false);
const[recos,setRecos]=useState([]);
const[sortedRecos,setSortedRecos]=useState([]);
const[sortMode,setSortMode]=useState("match");
const[chatHistory,setChatHistory]=useState([]);
const[chatInput,setChatInput]=useState("");
const[busy,setBusy]=useState(false);
const toastTimer=useRef(null);
const buildCtx=useCallback((fa,dq)=>{const lines=[Budget: ${freeVals.budget}EUR,Age: ${freeVals.age},Ville: ${freeVals.city},Hobby: ${freeVals.hobby||"?"}];fa.forEach((q,i)=>q&&lines.push(Q${i+1}: ${q.q} -> ${q.answer}));dq.forEach((q,i)=>q?.answer&&lines.push(QD${i+1}: ${q.q} -> ${q.answer}));return lines.join("\n")},[freeVals]);
const calcConf=useCallback((fa,dq)=>Math.min(Math.round(((fa.filter(Boolean).length+dq.filter(q=>q?.answer).length)/(FIXED_BQ.length+7))*100),100),[]);
const nextFree=()=>{const step=FREE_STEPS[curFree];const err=step.validate(freeVals[step.id]||"");if(err){setFreeErr(err);return}setFreeErr("");if(curFree+1>=FREE_STEPS.length)setScreen("binary");else setCurFree(c=>c+1)};
const binAnswer=async(ans)=>{if(thinking||busy)return;if(inDynamic){const dIdx=curBin-11;const newDQ=[...dynQuestions];newDQ[dIdx]={...newDQ[dIdx],answer:ans};setDynQuestions(newDQ);const nc=calcConf(fixedAnswers,newDQ);setConf(nc);if(dIdx+1>=7||nc>=95){setScreen("syn");await genRecos(fixedAnswers,newDQ)}else{setCurBin(c=>c+1);await fetchDynQ(fixedAnswers,newDQ)}return}const fq=FIXED_BQ[curBin];const newFA=[...fixedAnswers];newFA[curBin]={q:fq.q,answer:ans,theme:fq.theme};setFixedAnswers(newFA);setConf(calcConf(newFA,dynQuestions));if(curBin+1>=FIXED_BQ.length){setInDynamic(true);setCurBin(11);await fetchDynQ(newFA,[])}else{setCurBin(c=>c+1);setConfPhase(FIXED_BQ[curBin+1]?.phase||"Analyse")}};
const fetchDynQ=async(fa,dq)=>{setThinking(true);try{const raw=await callProxy([{role:"user",content:buildCtx(fa,dq)}],Tu es GiftMind OS. Gnre UNE question binaire OUI/NON. Rponds UNIQUEMENT en JSON: {"question":"...","phase":"..."},MAX_TOKENS_DYN);const res=safeParseJson(raw);if(res?.question){setDynQuestions(prev=>[...prev,{q:res.question,answer:null}]);setConfPhase(res.phase||"Analyse")}else{setScreen("syn");await genRecos(fa,dq)}}catch{setScreen("syn");await genRecos(fa,dq)}finally{setThinking(false)}};
const genRecos=async(fa,dq)=>{try{const raw=await callProxy([{role:"user",content:buildCtx(fa,dq)}],Tu es GiftMind OS expert cadeaux. Gnre 20 cadeaux. JSON uniquement: {"recos":[{"item_name":"...","description":"...","match_pct":90,"prix_num":350,"prix_estime":"350","luxe_level":4}]},MAX_TOKENS_RECOS);const parsed=safeParseJson(raw);if(parsed?.recos?.length){const sorted=[...parsed.recos].sort((a,b)=>b.match_pct-a.match_pct);setRecos(parsed.recos);setSortedRecos(sorted);setScreen("chat")}else setScreen("intro")}catch{setScreen("intro")}};
const sendChat=async()=>{const query=chatInput.trim();if(!query||busy)return;setChatInput("");setBusy(true);const newH=[...chatHistory,{role:"user",content:query}];setChatHistory(newH);try{const ans=await callProxy(newH,Tu es GiftMind OS. Contexte: ${buildCtx(fixedAnswers,dynQuestions)},MAX_TOKENS_CHAT);setChatHistory(h=>[...h,{role:"assistant",content:ans}])}catch{}finally{setBusy(false)}};
const C={bg:"#0A0A0A",surface:"#111",text:"#F0F0F0",muted:"#666",border:"#222",red:"#FF4D4F"};
const s={page:{background:C.bg,color:C.text,minHeight:"100vh",fontFamily:"'DM Mono',monospace",display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",padding:"40px 20px"},card:{width:"100%",maxWidth:560},label:{fontSize:11,letterSpacing:"0.15em",color:C.muted,textTransform:"uppercase"},h1:{fontSize:"2.4rem",fontWeight:700,letterSpacing:"-0.04em",margin:"8px 0 24px"},h2:{fontSize:"1.5rem",fontWeight:500,lineHeight:1.4,margin:"12px 0 8px"},hint:{fontSize:13,color:C.muted,marginBottom:28},input:{background:"transparent",border:"none",borderBottom:1px solid ${C.border},color:C.text,fontSize:20,padding:"10px 0",outline:"none",width:"100%",fontFamily:"inherit"},btnP:{padding:"12px 28px",background:C.text,color:C.bg,border:"none",borderRadius:4,cursor:"pointer",fontFamily:"inherit",fontSize:14},btnG:{background:"none",border:"none",color:C.muted,cursor:"pointer",fontFamily:"inherit",fontSize:14,padding:"6px 0"},btnB:{flex:1,padding:"14px 0",borderRadius:4,cursor:"pointer",background:C.surface,color:C.text,border:1px solid ${C.border},fontFamily:"inherit",fontSize:14}};
if(screen==="intro")return(<div style={s.page}><div style={s.card}><p style={s.label}>GiftMind OS  v6.0</p><h1 style={s.h1}>Le cadeau parfait,<br/>par algorithme.</h1><p style={{...s.hint,maxWidth:380}}>18 questions adaptatives. 20 recommandations sur-mesure.</p><button style={s.btnP} onClick={()=>setScreen("free")}>Initialiser le protocole </button></div></div>);
if(screen==="free"){const step=FREE_STEPS[curFree];return(<div style={s.page}><div style={s.card}><p style={s.label}>{step.num}  {step.label}</p><h2 style={s.h2}>{step.q}</h2><p style={s.hint}>{step.hint}</p>{step.type==="textarea"?<textarea rows={3} style={{...s.input,resize:"none"}} placeholder={step.placeholder} value={freeVals[step.id]||""} onChange={e=>setFreeVals({...freeVals,[step.id]:e.target.value})}/>:<input style={s.input} type={step.type} placeholder={step.placeholder} value={freeVals[step.id]||""} onChange={e=>setFreeVals({...freeVals,[step.id]:e.target.value})} onKeyDown={e=>e.key==="Enter"&&nextFree()}/>}{freeErr&&<p style={{color:C.red,fontSize:12,marginTop:8}}>{freeErr}</p>}<div style={{display:"flex",justifyContent:"space-between",marginTop:36}}><button style={s.btnG} onClick={()=>curFree>0&&setCurFree(c=>c-1)}> Retour</button><button style={s.btnP} onClick={nextFree}>Continuer </button></div></div></div>)}
if(screen==="binary"){const currentQ=inDynamic?dynQuestions[curBin-11]:FIXED_BQ[curBin];return(<div style={s.page}><div style={s.card}><p style={s.label}>{conf}%  {confPhase}</p><h2 style={{...s.h2,marginTop:16,minHeight:60}}>{thinking?<span>Gnration</span>:currentQ?.q}</h2>{!thinking&&<div style={{display:"flex",gap:8,marginTop:28}}><button style={s.btnB} onClick={()=>binAnswer("OUI")}>Oui</button><button style={s.btnB} onClick={()=>binAnswer("NON")}>Non</button><button style={{...s.btnB,color:C.muted}} onClick={()=>binAnswer("PASSER")}>Passer</button></div>}</div></div>)}
if(screen==="syn")return(<div style={s.page}><div style={{textAlign:"center"}}><p style={s.label}>GiftMind OS</p><h2 style={{...s.h2,marginTop:12}}>Analyse en cours</h2></div></div>);
return(<div style={{background:C.bg,color:C.text,minHeight:"100vh",fontFamily:"'DM Mono',monospace"}}><div style={{borderBottom:1px solid ${C.border},padding:"20px 32px",display:"flex",justifyContent:"space-between"}}><div><p style={s.label}>GiftMind OS  Rsultats</p><h2 style={{fontSize:"1.1rem",marginTop:4}}>{recos.length} recommandations  {freeVals.budget}  {freeVals.age}ans  {freeVals.city}</h2></div><button style={s.btnG} onClick={()=>{setScreen("intro");setCurFree(0);setFreeVals({budget:"",age:"",city:"",hobby:""});setCurBin(0);setInDynamic(false);setFixedAnswers([]);setDynQuestions([]);setRecos([]);setSortedRecos([]);setChatHistory([])}}>Rinitialiser</button></div><div style={{display:"flex",height:"calc(100vh - 65px)"}}><div style={{flex:1,overflowY:"auto",padding:"24px 32px"}}>{sortedRecos.map((r,idx)=><div key={idx} style={{padding:"16px 0",borderBottom:1px solid ${C.border}}}><div style={{display:"flex",justifyContent:"space-between"}}><div><h3 style={{fontSize:15}}>#{idx+1} {r.item_name}</h3><p style={{fontSize:13,color:C.muted,marginTop:4}}>{r.description}</p></div><div style={{textAlign:"right",marginLeft:16}}><div>{r.prix_estime}</div><div style={{fontSize:11,color:C.muted}}>{r.match_pct}% match</div></div></div></div>)}</div><div style={{width:320,borderLeft:1px solid ${C.border},display:"flex",flexDirection:"column"}}><div style={{padding:"16px 20px",borderBottom:1px solid ${C.border}}}><p style={s.label}>Assistant</p></div><div style={{flex:1,overflowY:"auto",padding:"16px 20px"}}>{chatHistory.map((msg,i)=><div key={i} style={{marginBottom:14,padding:"10px 14px",background:msg.role==="user"?C.surface:"transparent",border:msg.role==="assistant"?1px solid ${C.border}:"none",fontSize:13,borderRadius:4}}><p style={{fontSize:10,color:C.muted,marginBottom:4}}>{msg.role==="user"?"VOUS":"GIFTMIND"}</p>{msg.content}</div>)}{busy&&<div style={{fontSize:13,color:C.muted}}>Analyse</div>}</div><div style={{padding:"12px 16px",borderTop:1px solid ${C.border}}}><div style={{display:"flex",gap:8}}><input style={{flex:1,background:C.surface,border:1px solid ${C.border},color:C.text,padding:"10px 12px",borderRadius:4,fontFamily:"inherit",fontSize:13,outline:"none"}} placeholder="Question" value={chatInput} onChange={e=>setChatInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&sendChat()} disabled={busy}/><button style={{...s.btnP,padding:"10px 14px"}} onClick={sendChat} disabled={busy}></button></div></div></div></div></div>)}
